stages:
  - test
  - build
  - push

variables:
  IMAGE_NAME: "$DOCKER_USERNAME/app"
  IMAGE_TAG: "$CI_COMMIT_SHA"
  DOCKER_TLS_CERTDIR: ""

test:
  stage: test
  image: python:3.11-slim
  script:
    - pip install -r requirements.txt
    - export PYTHONPATH="$PYTHONPATH:$(pwd)"
    - pytest -v

build:
  stage: build
  image: docker:27.0.3
  services:
    - name: docker:27.0.3-dind
      command: ["--tls=false"]
  script:
    - docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$IMAGE_TAG .

push:
  stage: push
  image: docker:27.0.3
  services:
    - docker:27.0.3-dind
      command: ["--tls=false"]
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker push $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$IMAGE_TAG
